export const SearchTrendObject = [
  {
    nome: 'Rio de Janeiro',
    mes: [
      {
        nome: 'Janeiro',
        precoInicial: '220',
        precoFinal: '850',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Fevereiro',
        precoInicial: '310',
        precoFinal: '780',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Março',
        precoInicial: '400',
        precoFinal: '650',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Abril',
        precoInicial: '420',
        precoFinal: '550',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Maio',
        precoInicial: '300',
        precoFinal: '800',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Junho',
        precoInicial: '210',
        precoFinal: '820',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Julho',
        precoInicial: '420',
        precoFinal: '780',
        texto: 'até',
        moeda: 'R$',
      },
    ],
  },
  {
    nome: 'São Paulo',
    mes: [
      {
        nome: 'Janeiro',
        precoInicial: '250',
        precoFinal: '900',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Fevereiro',
        precoInicial: '330',
        precoFinal: '850',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Março',
        precoInicial: '410',
        precoFinal: '700',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Abril',
        precoInicial: '150',
        precoFinal: '600',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Maio',
        precoInicial: '350',
        precoFinal: '880',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Junho',
        precoInicial: '230',
        precoFinal: '870',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Julho',
        precoInicial: '440',
        precoFinal: '820',
        texto: 'até',
        moeda: 'R$',
      },
    ],
  },
  {
    nome: 'Bahia',
    mes: [
      {
        nome: 'Janeiro',
        precoInicial: '180',
        precoFinal: '750',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Fevereiro',
        precoInicial: '270',
        precoFinal: '720',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Março',
        precoInicial: '360',
        precoFinal: '620',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Abril',
        precoInicial: '300',
        precoFinal: '500',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Maio',
        precoInicial: '280',
        precoFinal: '770',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Junho',
        precoInicial: '290',
        precoFinal: '780',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Julho',
        precoInicial: '380',
        precoFinal: '760',
        texto: 'até',
        moeda: 'R$',
      },
    ],
  },
  {
    nome: 'Espírito Santo',
    mes: [
      {
        nome: 'Janeiro',
        precoInicial: '200',
        precoFinal: '800',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Fevereiro',
        precoInicial: '290',
        precoFinal: '760',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Março',
        precoInicial: '390',
        precoFinal: '650',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Abril',
        precoInicial: '140',
        precoFinal: '580',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Maio',
        precoInicial: '320',
        precoFinal: '850',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Junho',
        precoInicial: '210',
        precoFinal: '820',
        texto: 'até',
        moeda: 'R$',
      },
      {
        nome: 'Julho',
        precoInicial: '430',
        precoFinal: '780',
        texto: 'até',
        moeda: 'R$',
      },
    ],
  },
];
